"""Build a self-contained HTML test-coverage scorecard from artifacts/grades.json.

Opens offline in any browser. Run `python zttd.py grade` first to produce
grades.json.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from _common import project_root

GRADE_COLOR = {"A": "#1a7f37", "B": "#9a6700", "F": "#cf222e"}


def main(argv: list[str]) -> int:
    root = project_root()
    gj = root / "artifacts" / "grades.json"
    if not gj.exists():
        sys.exit("zoom-ttd: artifacts/grades.json not found. Run `python zttd.py grade` first.")
    data = json.loads(gj.read_text(encoding="utf-8"))
    run, models = data["run"], data["models"]

    gate_color = "#1a7f37" if run["gate"] == "PASS" else "#cf222e"

    rows = []
    for m in models:
        t = m["tests"]
        rows.append(f"""
      <tr>
        <td><code>{m['model']}</code></td>
        <td>{m['layer']}</td>
        <td style="text-align:center"><span class="grade" style="background:{GRADE_COLOR.get(m['grade'],'#666')}">{m['grade']}</span></td>
        <td>{m['status']}</td>
        <td>{', '.join(m['categories']) or '&ndash;'}</td>
        <td>{', '.join(m['categories_covered']) or '&ndash;'}</td>
        <td style="text-align:center">{t['generic']} / {t['singular']} / {t['unit']}</td>
      </tr>""")

    html = f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>zoom-ttd Coverage Scorecard</title>
<style>
  body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; margin: 0; background:#f6f8fa; color:#1f2328; }}
  header {{ background:#0b5cff; color:#fff; padding:24px 32px; }}
  header h1 {{ margin:0; font-size:22px; }}
  header p {{ margin:4px 0 0; opacity:.9; font-size:13px; }}
  .wrap {{ max-width:1080px; margin:24px auto; padding:0 16px; }}
  .cards {{ display:flex; gap:16px; margin-bottom:24px; flex-wrap:wrap; }}
  .card {{ background:#fff; border:1px solid #d0d7de; border-radius:10px; padding:16px 20px; flex:1; min-width:140px; }}
  .card .n {{ font-size:30px; font-weight:700; }}
  .card .l {{ font-size:12px; text-transform:uppercase; letter-spacing:.04em; color:#656d76; }}
  .gate {{ color:#fff; padding:4px 12px; border-radius:20px; font-weight:700; background:{gate_color}; }}
  table {{ width:100%; border-collapse:collapse; background:#fff; border:1px solid #d0d7de; border-radius:10px; overflow:hidden; }}
  th, td {{ padding:10px 12px; text-align:left; border-bottom:1px solid #eaeef2; font-size:13px; }}
  th {{ background:#f6f8fa; font-size:11px; text-transform:uppercase; letter-spacing:.04em; color:#656d76; }}
  code {{ background:#eef1f4; padding:1px 5px; border-radius:4px; font-size:12px; }}
  .grade {{ color:#fff; font-weight:700; padding:2px 9px; border-radius:6px; display:inline-block; min-width:18px; text-align:center; }}
  .lin {{ background:#fff; border:1px solid #d0d7de; border-radius:10px; padding:16px 20px; margin-top:24px; font-size:13px; }}
  .lin code {{ font-size:12px; }}
  footer {{ text-align:center; color:#656d76; font-size:12px; margin:24px; }}
</style></head>
<body>
<header>
  <h1>Zoom Test-Then-Deploy &mdash; Coverage Scorecard</h1>
  <p>Generated by the zoom-ttd grader &middot; every model graded A/B/F on the logic it actually contains</p>
</header>
<div class="wrap">
  <div class="cards">
    <div class="card"><div class="l">Gate</div><div class="n"><span class="gate">{run['gate']}</span></div></div>
    <div class="card"><div class="l">Models</div><div class="n">{run['models_total']}</div></div>
    <div class="card"><div class="l">Grade A</div><div class="n" style="color:#1a7f37">{run['grade_A']}</div></div>
    <div class="card"><div class="l">Grade B</div><div class="n" style="color:#9a6700">{run['grade_B']}</div></div>
    <div class="card"><div class="l">Grade F</div><div class="n" style="color:#cf222e">{run['grade_F']}</div></div>
  </div>

  <table>
    <thead><tr>
      <th>Model</th><th>Layer</th><th>Grade</th><th>Status</th>
      <th>Logic categories</th><th>Unit-covered</th><th>Tests (g/s/u)</th>
    </tr></thead>
    <tbody>{''.join(rows)}
    </tbody>
  </table>

  <div class="lin">
    <strong>Medallion lineage</strong><br>
    <code>seeds (raw_*)</code> &rarr; <code>bronze (brz_*)</code> &rarr;
    <code>silver (slv_*)</code> &rarr; <code>gold (dim_*, fct_meetings)</code><br><br>
    <strong>Grades:</strong> A = functional + unit test (logic categories exercised) &middot;
    B = tested but no unit test &middot; F = untested (blocked by the on-run-start interceptor).
  </div>
</div>
<footer>zoom-ttd &middot; tests (g/s/u) = generic / singular / unit</footer>
</body></html>"""

    out = root / "artifacts" / "zoom_ttd_scorecard.html"
    out.parent.mkdir(exist_ok=True)
    out.write_text(html, encoding="utf-8")
    print(f"zoom-ttd: wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
